############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "News"
url = "news/"
weight = 2

[[main]]
name = "Leaderboard"
url = "leaderboard/"
weight = 3

[[main]]
name = "Datasets"
url = "dataset/"
weight = 4

[[main]]
name = "Discussions"
url = "https://github.com/math-eval/MathEval/discussions"
weight = 5

[[main]]
name = "Contact"
url = "/#contact"
weight = 6
